### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by MatheusRich** [jinroq/msgraph#9]
Hey, thanks for the gem! I'm not a Japanese speaker, so I mostly followed the slides on [your talk](https://www.youtube.com/watch?v=TrVhnrTPtoI).

Could you provide some basic instructions on how to use the gem? For instance, should I do the OAuth flow on my own to get the token, or does the gem supports this automatically?

Thanks!

**Comment by jinroq** [comment]
@MatheusRich 

Thanks for the comment!

Before I go any further, I have no motivation to maintain this gem. Therefore, I don't intend to create documentation either.

There are two main reasons.

Microsoft no longer supports Ruby with Microsoft Graph (see: https://learn.microsoft.com/en-us/graph/tutorials#delegated-user-authentication). Microsoft Graph no longer supports Ruby, and the official gem has declared "[NOT actively supported](https://github.com/microsoftgraph/msgraph-sdk-ruby/issues/69)".
This was reason enough for me to lose motivation.

There has been some recent activity in the Microsoft Graph SDK for Ruby, but I am not going to get involved.
